app.py
"""
authors: Quintin Dunn, Zeke Mccrary
date: 9/16/23
description: Entry point for the program, registers blueprints, runs the dev server
"""

import mimetypes
from flask import Flask
from routes import register_routes
import config

mimetypes.add_type("application/javascript", ".js")
mimetypes.add_type("text/css", ".css")

app = Flask(__name__)

# REGISTER CONFIG SETTINGS
app.secret_key = config.FLASK_SECRET


# Register routes
register_routes(app)


if __name__ == '__main__':
    app.run(host=config.FLASK_HOST, port=config.FLASK_PORT, debug=config.FLASK_DEBUG)

routes/__init__.py
"""
authors: Quintin Dunn, Zeke Mccrary
date: 9/16/23
description: Defines the routes for all the modules.
"""

import flask

from .home import home
from .vector2d import vector2d
from .graphs import graphs


def register_routes(app: flask.Flask):
    """
    Iterates through the defined routes and register them on the app.
    :param app: flask.Flask object to register the blueprints on
    :return: None
    """
    for blueprint, prefix in routes:
        if len(prefix) > 0:
            app.register_blueprint(blueprint, url_prefix=prefix)
        else:
            app.register_blueprint(blueprint)


routes = [
    (home, ""),
    (vector2d, "/2dvectors"),
    (graphs, "/graphs")
]

routes/graphs.py
"""
authors: Quintin Dunn, Zeke Mccrary
date: 9/19/23
description: Routes for graphs
"""


from flask import Blueprint, render_template

graphs = Blueprint("graphs", __name__)


@graphs.route("/")  # http://localhost/graphs/
async def index():
    """
    Main page for vectors, url: http://localhost/graphs/
    :return:
    """
    return render_template("graphs/index.html")


@graphs.route("/dva/")  # http://localhost/graphs/dva
def dva_graphs():
    """
    VT DT AT graphing, url: http://localhost/graphs/dva
    :return:
    """
    return render_template("graphs/dva_graphs.html")

routes/home.py
"""
authors: Quintin Dunn, Zeke Mccrary
date: 9/16/23
description: Routes for home
"""

from flask import Blueprint, render_template

home = Blueprint("home", __name__)


@home.route("/")
async def index():
    """
    Main home page.
    :return: render_template
    """
    return render_template("home/index.html")

routes/vector2d.py
"""
authors: Quintin Dunn, Zeke Mccrary
date: 9/16/23
description: Routes for 2d vectors
"""


from flask import Blueprint, render_template

vector2d = Blueprint("vector2d", __name__)


@vector2d.route("/")  # http://localhost/2dvectors/
async def index():
    """
    Main page for vectors, url: http://localhost/2dvectors/
    :return:
    """
    return render_template("vector2d/index.html")


@vector2d.route("/2dcalculator")  # http://localhost/2dvectors/2dcalculator
def vector_addition_calculator():
    """
    Multi-vector addition calculator, url: http://localhost/2dvectors/2dcalculator
    :return:
    """
    return render_template("vector2d/vector_addition_calculator.html")

templates/core/core.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}APhysics Tools{% endblock title %}</title>
    <script src="{{ url_for('static', filename="./core/js/core.js") }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename="./core/css/core.css") }}">
    {% block head %}{% endblock head %}
</head>
<body>
    <div class="nav-bar">
        <a href="{{ url_for("home.index") }}" class="no-anchor-decor">
            <div class="nav-bar-title">
                <h1>APHYSICS</h1>
                <h1>TOOLS</h1>
            </div>
        </a>
        <div class="nav-bar-content">
            {% block navbaritems %}
            {% endblock navbaritems %}
        </div>
    </div>
    <div class="content-parent">
        <div class="content-child">
            {% block content %}
            {% endblock content %}
        </div>
    </div>
</body>
</html>

templates/graphs/dva_graphs.html
{% extends 'graphs/graph_template.html' %}
{% block title %} {% endblock title %}

{% block head %}
    <script src="/static/node_modules/mathjs/lib/browser/math.js" type="text/javascript"></script>

    <script type="module" src="{{ url_for("static", filename="./graphs/js/dva_graphs/dva_graphs.js") }}"></script>
    <script src="{{ url_for("static", filename="./graphs/js/dva_graphs/input_manager.js") }}" defer></script>

    <link rel="stylesheet" href="{{ url_for("static", filename="./graphs/css/dva_graphs/dva_graphs.css") }}">
{% endblock head %}

{% block content %}
    <div class="page-content">
        <div id="settings">
            <button class="zoom-button" id="zoom-in">Zoom In</button>
            <input type="number" id="factor" value="2" min="1">
            <button class="zoom-button" id="zoom-out">Zoom Out</button>
        </div>
        <br>
        <div id="container"></div>

        <div id="mouse-stuff">
            <span class="mouse-coord"> X: <input type="number" id="mouse-x" value=""> </span>
            <span class="mouse-coord"> Y: <input type="number" id="mouse-y" value=""> </span>
        </div>
        <div class="function-data">
            <table id="function-table"><tbody>
                <tr class="table-row">
                    <td class="table-box"><input class="table-input" placeholder="Equation" name="equation"></td>
                    <td class="table-box"><input class="table-input" placeholder="Condition" name="condition"></td>
                </tr>
            </tbody></table>
        </div>
        <div class="graph-btn">
            <button id="graph-btn">Graph</button>
        </div>
        <div id="error-div"></div>
    </div>
{% endblock content %}

templates/graphs/graph_template.html
{% extends 'core/core.html' %}
{% block title %}Graphing{% endblock title %}

{% block head %} {% endblock head %}

{% block navbaritems %}
    <a class="no-anchor-decor" href="{{ url_for("graphs.index") }}">
        <div class="nav-bar-item">
            <h2>Graphs</h2>
        </div>
    </a>
    <a class="no-anchor-decor" href="{{ url_for("graphs.dva_graphs") }}">
        <div class="nav-bar-item">
            <h2>DVA Graphs</h2>
        </div>
    </a>
{% endblock navbaritems %}

{% block content %}

{% endblock content %}

templates/graphs/index.html
{% extends 'graphs/graph_template.html' %}
{% block title %} {% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename="./graphs/css/graphs_home/graphs_home.css") }}">
{% endblock head %}

{% block content %}
 <div class="page-content">
        <div class="heading">
            <h1>About Displacement/Velocity/Acceleration Time graphs</h1>
        </div>
        <hr style="width: 100%; margin: 2vh 0;">
        <div class="info">
            <p>Displacement/Time, Velocity/Time, and Acceleration/Time (DVA-T) graphs are a way of visually representing the movement of an object, each graph represents a different aspect of the objects motion. You can transform inbetween the graphs using both visual and computational methods, however for the AP Physics 1 course the visual method should be more than accurate enough and is a lot simpler.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eu mi bibendum neque egestas. Et malesuada fames ac turpis egestas. Enim eu turpis egestas pretium aenean pharetra magna. Placerat in egestas erat imperdiet. Sed libero enim sed faucibus. Nunc mattis enim ut tellus. Convallis posuere morbi leo urna molestie at elementum eu. Adipiscing vitae proin sagittis nisl rhoncus mattis. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque. Scelerisque fermentum dui faucibus in ornare quam viverra orci. Here is an example of a Displacement/Time graph:</p>
            <img src="#need_an_image" alt="Example of a labeled/explained displacement/time graph.">

            <p>Nunc consequat interdum varius sit amet mattis. Diam vulputate ut pharetra sit amet aliquam id. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing. At tellus at urna condimentum mattis pellentesque id. Netus et malesuada fames ac turpis egestas sed tempus. Ac tortor vitae purus faucibus ornare suspendisse. Auctor eu augue ut lectus. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Here is an example of a Velocity/Time graph:</p>
            <img src="#need_an_image" alt="Example of a labeled/explained velocity/time graph.">

            <p>Turpis egestas sed tempus urna et pharetra pharetra. Convallis aenean et tortor at. Ultrices dui sapien eget mi proin sed libero enim. Elit sed vulputate mi sit. Accumsan tortor posuere ac ut consequat. Vel quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Faucibus scelerisque eleifend donec pretium vulputate. Here is a example of an Acceleration/Time graph:</p>
            <img src="#need_an_image" alt="Example image labeled/explain acceleration/time graph.">

            <p>Knowing how to interpret these graphs can greatly help you think a problem through, one of the best ways to understand something is to tinker with it! Luckily we have a <a href="{{ url_for("graphs.dva_graphs") }}" class="no-anchor-decor" style="color:cadetblue;">tool</a> to help you understand how the graphs transform into one another!</p>

            <p>To transform between the graphs visually you'll want to Aliquet nec ullamcorper sit amet risus nullam eget felis eget. Commodo sed egestas egestas fringilla phasellus faucibus scelerisque. Sollicitudin tempor id eu nisl nunc mi ipsum. Id venenatis a condimentum vitae sapien pellentesque habitant morbi tristique. Integer feugiat scelerisque varius morbi enim nunc faucibus a pellentesque. Amet consectetur adipiscing elit duis tristique sollicitudin nibh sit amet.</p>
            <ul>
                <li>1. Do thing 1</li>
                <li>2. Do thing 2</li>
                <li>3. Do thing 3</li>
                <li>4. Do thing 4</li>
                <li>5. Do thing 5</li>
            </ul>
            <img src="#need_an_image" alt="Example image 1 of the steps to visually transform the graphs."><br>
            <img src="#need_an_image" alt="Example image 2 of the steps to visually transform the graphs."><br>
            <img src="#need_an_image" alt="Example image 3 of the steps to visually transform the graphs.">

            <p>To transform between the graphs computationally you'll want to ask Zeke...</p>
            <ul>
                <li>1. Do thing 1</li>
                <li>2. Do thing 2</li>
                <li>3. Do thing 3</li>
                <li>4. Do thing 4</li>
                <li>5. Do thing 5</li>
            </ul>

            <p style="margin-top: 4vh">The best way to learn is to tinker, click <a href="{{ url_for("graphs.dva_graphs") }}" class="no-anchor-decor" style="color:cadetblue;">here</a> to try out our <a href="{{ url_for("graphs.dva_graphs") }}" class="no-anchor-decor" style="color:cadetblue;">DVA-T graphing tool</a>!</p>
        </div>
    </div>
{% endblock content %}

templates/home/index.html
{% extends 'core/core.html' %}
{% block title %}Home{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename="./home/css/home.css") }}">
{% endblock head %}

{% block navbaritems %}
    <a class="no-anchor-decor" href="{{ url_for("vector2d.index") }}">
        <div class="nav-bar-item">
            <h2>2D Vectors</h2>
        </div>
    </a>
    <a class="no-anchor-decor" href="{{ url_for("graphs.index") }}">
        <div class="nav-bar-item">
            <h2>Graphing</h2>
        </div>
    </a>
{% endblock navbaritems %}

{% block content %}
    <div class="page-content">
        <div class="heading">
            <div class="title">
                <a href="{{ url_for("home.index") }}" class="no-anchor-decor">
                    <h1><span>AP</span><span>hysics</span> </h1>
                    <h1>Tools</h1>
                    <hr style="width: 100%;">
                </a>
            </div>
        </div>
        <div class="about">
                <div class="what-is">
                    <h1>What is APhysics Tools</h1>
                    <p>APhysics Tools is an <a href="https://github.com/quintindunn/aphysicsweb" class="no-anchor-decor" style="color:cadetblue;">open source</a> collection of simple to use tools for the AP Physics 1 course, it houses a variety of tools, such as a 2D Vector addition calculator, some other thing, another thing, and more! Additionally, there is documentation on all the used equations, when those equations can be used, and different ways to approach a given problem!</p>
                </div>
                <div class="about-the-creators">
                    <h1>About Us</h1>
                    <p>APhysics Tools is being developed, and maintained by two current AP Physics 1 students. This project will be continuously changing, with the addition of new features such as new calculators, simulations, and documentations.</p>
                </div>
        </div>
    </div>
{% endblock content %}

templates/vector2d/index.html
{% extends 'vector2d/vector_template.html' %}
{% block title %}Information on 2D Vectors{% endblock title %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename="./vector2d/css/2dvectors_home/2dvectors_home.css") }}">
{% endblock head %}

{% block content %}
    <div class="page-content">
        <div class="heading">
            <h1>What are 2-Dimensional Vectors</h1>
        </div>
        <hr style="width: 100%; margin: 2vh 0;">
        <div class="info">
            <p>2D Vectors are a way of representing motion on a 2-dimensional plane. Vectors, or polar coordinates, consist of two numbers, a distance or velocity and an angle. While working with them can simplify some problems, doing conversions between them and Cartesian coordinates can be repetitive and time-consuming.</p>
            <p>The vectors are represented with a distance/velocity and an angle in a plethora of ways, though here will be represented in a distance @ angle format, i.e. 25m@45° representing 25 meters at a 45-degree angle. Additionally, it can be represented in a diagram like this:</p>
            <img src="#need_an_image" alt="Example image of a vector diagram">

            <p>These vectors can be added using a graphical method, or a computational method. While the graphical method might be easier to wrap your head around, you can quickly lose precision and the more vectors added together, the worse it will most likely get. When adding vectors graphically it's important to remember the rule to line the vectors up tip to tail. What this means is that every vector should be placed with the start of the vector being aligned with the end of the previous vector. The full steps to add vectors graphically are as follows:</p>
            {# ToDo: Add the steps for graphically adding vectors. #}
            <ul>
                <li>1. Do thing 1</li>
                <li>2. Do thing 2</li>
                <li>3. Do thing 3</li>
                <li>4. Do thing 4</li>
                <li>5. Do thing 5</li>
            </ul>

            {# ToDo: Create an example image of adding vectors graphically. #}
            <img src="#need_an_image" alt="Example image of adding vectors graphically">
            <p>While a tiny bit more work to understand, a much more precise method for adding the together is through math, mostly staring trigonometry. Consisting of sin, cos, tan, and the pythagorean theorem. The steps to add vectors mathematically are too fairly simple.</p>
            {# ToDo: Add the steps for mathematically adding vectors. #}
            <ul>
                <li>1. Do thing 1</li>
                <li>2. Do thing 2</li>
                <li>3. Do thing 3</li>
                <li>4. Do thing 4</li>
                <li>5. Do thing 5</li>
            </ul>
            {# ToDo: Create an example image of adding vectors mathematically. #}
            <img src="#need_an_image" alt="Example image of adding vectors mathematically">

            <p>Thoroughly knowing how to add vectors mathematically is vital for AP Physics 1, however once you know the ropes you can use our <a href="{{ url_for("vector2d.vector_addition_calculator") }}" class="no-anchor-decor" style="color:cadetblue;">calculator</a> which can add as many vectors together as you want, and will also show you the steps!</p>
        </div>
    </div>

{% endblock content %}

templates/vector2d/vector_addition_calculator.html
{% extends 'vector2d/vector_template.html' %}
{% block title %}2D Vector Addition Calculator{% endblock title %}

{% block head %}
    <script src="{{ url_for('static', filename="./vector2d/js/vector_addition_calculator/vector_addition_calculator.js") }}" defer></script>
    <link rel="stylesheet" href="{{ url_for('static', filename="./vector2d/css/vector_addition_calculator/vector_addition_calculator.css") }}">
{% endblock head %}

{% block content %}
    <div class="page-content">
        <div class="heading">
            <h1>2D Vector Addition Calculator</h1>
            <p>Mathematical 2D vector addition is done using sin and cos functions to convert each vector to Cartesian coordinates, these are then added back together and converted back to polar coordinates, more information on this can be found <a href="{{ url_for("vector2d.index") }}" class="no-anchor-decor" style="color:cadetblue;">here</a>.</p>
        </div>
        <div id="options">
            <div class="option-div" id="show-math" style="background-color: lightgray;">Show Calculations</div>
        </div>
        <hr style="width: 100%; margin: 2vh 0;">
        <table id="vector-table"><tbody>
            <tr class="table-row">
                <td class="table-box"><input class="table-input" placeholder="Magnitude" name="magnitude"></td>
                <td class="table-box"><input class="table-input" placeholder="Direction (degrees)" name="direction"></td>
            </tr>
        </tbody></table>
        <br>
        <div class="controls">
            <button id="calculate-button">Calculate</button>
            <button id="clear-button">Clear</button>
        </div>
        <br>
        <div id="output-div" style="color: black"></div>
        <div id="steps-div" data-active="false"></div>
    </div>
{% endblock content %}

templates/vector2d/vector_template.html
{% extends 'core/core.html' %}
{% block title %}2D Vector Tools{% endblock title %}

{% block head %} {% endblock head %}

{% block navbaritems %}
    <a class="no-anchor-decor" href="{{ url_for("vector2d.index") }}">
        <div class="nav-bar-item">
            <h2>2D Vector</h2>
        </div>
    </a>
    <a class="no-anchor-decor" href="{{ url_for("vector2d.vector_addition_calculator") }}">
        <div class="nav-bar-item">
            <h2>2D Vectors Calculator</h2>
        </div>
    </a>
{% endblock navbaritems %}

{% block content %}

{% endblock content %}